name: (Docker) Build U-Boot (Dev)
# ${{ github.workspace }} - > ${{ env.GITHUB_WORKSPACE }}

permissions:
  contents: write

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device_branch:
        description: "Select device branch"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - 360t7
          - livinet_zr-3020
          - cetron_ct3003
          - jcg_q30
          - konka_komi-a31
          - wr30u
          - imou_lc-hx3001
          - clt_r30b1
          - abt_asr3000
          - cmcc_a10
          - cmcc_rax3000m
          - cmcc_rax3000m-emmc
          - h3c_magic-nx30-pro
          - ax3000t
          - redmi_ax6000
          - tplink_tl-xdr608x
          - ruijie_rg-x60-pro
          - jdcloud_re-cp-03
          - glinet_gl-mt6000
          - nokia_ea0326gmp
          - ruijie_rg-x30e
          - ruijie_rg-x30e-pro
          - tplink_tl-xtr8488
          - newland_nl-wr8103
          - honor_fur-602
          - newland_nl-wr9103
          - cmcc_xr30
          - cmcc_xr30-emmc
          - zyxel_ex5700
          - openembed_som7981
          - glinet_gl-mt3000
          - glinet_gl-mt2500
          - ax3000t_an8855
          - ruijie_rg-x60
          - cudy_tr3000-v1
          - netcore_n60
          - netcore_n60-pro
          - ruijie_ew-6000gx-pro
      custom_env:
        description: "key=value;key=value"
        type: string
        required: false
        default: ""
      runner_image:
        description: "Runner Image"
        type: string
        required: false
        default: "ubuntu-latest"
  workflow_call:
    inputs:
      device_branch:
        description: "Select device branch"
        required: true
        type: string
      custom_env:
        description: "key=value;key=value"
        type: string
        required: false
      runner_image:
        description: "Runner Image"
        required: false
        type: string

run-name: U-Boot - ${{ inputs.device_branch || 'all' }}

env:
  device_branch: ${{ inputs.device_branch || 'all' }}
  custom_env: ${{ inputs.custom_env || '' }}

jobs:
  build:
    name: Build U-Boot - ${{ inputs.device_branch || 'all' }}
    runs-on: ${{ inputs.runner_image || 'ubuntu-latest' }}
    defaults:
      run:
        shell: bash
    container:
      image: ubuntu:devel
    env:
      DEBIAN_FRONTEND: noninteractive
      # ========= Toolchain Environment Variables ==========
      # ----- gcc -----
      gcc_purge: true
      gcc_install: true
      gcc_switch: false
      gcc_version: ""
      gcc_aarch64: true
      # ----- clang -----
      clang_purge: false
      clang_install: false
      clang_switch: false
      clang_version: ""
      # ----- jdk -----
      jdk_purge: false
      jdk_install: false
      jdk_switch: false
      jdk_version: ""
      # ----- docker -----
      docker_install: false
      qemu_install: false
      # ========= Workspace Environment Variables ==========
      # ----- Repository -----
      repo_target: "https://github.com/hanwckf/bl-mt798x"
      repo_target_branch: "master"
      repo_self: "https://github.com/${{ github.repository }}"
      repo_self_branch: "main"
      # ----- Build Path -----
      PATH_build: "/builder"
      PATH_target: "/builder/target"
      PATH_output: "/builder/output"
      PATH_backup: "/builder/backup"
      PATH_self: "/builder/self"
      release_md: "/builder/release.md"
    steps:
      - name: Docker Workspace All in One
        id: docker-workspace
        uses: Grinch27/github-actions/.github/actions/env-indocker@main
      # ========== General Environment Setup: End ==========
      - name: Clone Target Repository
        id: clonesys
        working-directory: ${{ env.PATH_build }}
        run: |
          echo -e "Current working directory: $(pwd)"

          # Clone target repository: without --depth=1
          git clone ${repo_target} ${PATH_target} --single-branch --branch=${repo_target_branch} 
          echo -e "repo_target: [ ${repo_target} ]\nBRANCH: [ ${repo_target_branch} ]"

          df -hT ${PWD}

      - name: Version of Target Repo
        id: git-rev
        uses: Grinch27/github-actions/.github/actions/git-rev@main
        with:
          path_target: ${{ env.PATH_target }}

      - name: Clone self
        id: clonediy
        working-directory: /
        run: |
          echo -e "Current working directory: $(pwd)"

          git clone ${repo_self} ${PATH_self} --single-branch --depth=1 --branch=${repo_self_branch}
          echo -e "repo_self: [ ${repo_self} ]\nBRANCH: [ ${repo_self_branch} ]"

          df -hT ${PWD}

      - name: Compile U-Boot Cycle
        id: compile
        env:
          device: ${{ env.device_branch }}
        working-directory: ${{ env.PATH_build }}
        run: |
          echo -e "Current working directory: $(pwd)"

          # [BOARD] = SOC | MULTI_LAYOUT | FIXED_MTDPARTS
          # local switch_MULTI_LAYOUT="0"
          # local switch_FIXED_MTDPARTS="0,1"
          declare -A BOARD_PARAMS=(
            ["360t7"]="mt7981|0|0,1" # 360 T7/T7U/T7M
            ["livinet_zr-3020"]="mt7981|0|0,1" # ZR3020
            ["cetron_ct3003"]="mt7981|0|0,1" # Cetron CT3003
            ["jcg_q30"]="mt7981|0|0,1" # JCG Q30 PRO
            ["konka_komi-a31"]="mt7981|0|0,1" # 康佳 KOMI-A31
            ["wr30u"]="mt7981|0,1|0,1" # 小米 WR30U/T/M [with MULTI_LAYOUT]
            ["imou_lc-hx3001"]="mt7981|0|0,1" # 乐橙 LC-HX3001
            ["clt_r30b1"]="mt7981|0,1|0,1" # 创联腾 CLT-R30B1 [with MULTI_LAYOUT]
            ["abt_asr3000"]="mt7981|0|0,1" # 安博通 ABT ASR3000
            ["cmcc_a10"]="mt7981|0|0,1" # CMCC A10
            ["cmcc_rax3000m"]="mt7981|0|0,1" # CMCC RAX3000M (SPI-NAND)
            ["cmcc_rax3000m-emmc"]="mt7981|0|0,1" # CMCC RAX3000M (EMMC)
            ["h3c_magic-nx30-pro"]="mt7981|0|0,1" # H3C NX30 Pro
            ["ax3000t"]="mt7981|0,1|0,1" # 小米 AX3000T [with MULTI_LAYOUT]
            ["redmi_ax6000"]="mt7986|0,1|0,1" # 红米 AX6000 [with MULTI_LAYOUT]
            ["tplink_tl-xdr608x"]="mt7986|0|0,1" # TP-LINK XDR4288/6086/6088
            ["ruijie_rg-x60-pro"]="mt7986|0,1|0,1" # Ruijie RG-X60 Pro [with MULTI_LAYOUT]
            ["jdcloud_re-cp-03"]="mt7986|0|0,1" # JDCloud RE-CP-03
            ["glinet_gl-mt6000"]="mt7986|0|0,1" # glinet gl-mt6000
            ["nokia_ea0326gmp"]="mt7981|0|1,0" # nokia ea0326gmp with and without FIXED_MTDPARTS
            ["ruijie_rg-x30e"]="mt7981|0,1|0,1" # Ruijie RG-X30E [with MULTI_LAYOUT]
            ["ruijie_rg-x30e-pro"]="mt7981|0,1|0,1" # Ruijie RG-X30E Pro [with MULTI_LAYOUT]
            ["tplink_tl-xtr8488"]="mt7986|0|0,1" # TP-Link TL-XTR8488
            ["newland_nl-wr8103"]="mt7981|0,1|0,1" # Newland NL-WR8103/MR3000D-CIq(256MB RAM version) [with MULTI_LAYOUT]
            ["honor_fur-602"]="mt7981|0,1|0,1" # HONOR FUR-602/603 (HONOR XT50/XU50/XC50) [with MULTI_LAYOUT]
            ["newland_nl-wr9103"]="mt7981|0,1|0,1" # Newland NL-WR9103 [with MULTI_LAYOUT]
            ["cmcc_xr30"]="mt7981|0|0,1" # CMCC XR30
            ["cmcc_xr30-emmc"]="mt7981|0|0,1" # CMCC XR30 eMMC
            ["zyxel_ex5700"]="mt7986|0|0,1" # Zyxel EX5700
            ["openembed_som7981"]="mt7981|0|0,1" # openembed som7981
            ["glinet_gl-mt3000"]="mt7981|0|0,1" # glinet gl-mt3000
            ["glinet_gl-mt2500"]="mt7981|0|0,1" # glinet gl-mt2500
            ["ax3000t_an8855"]="mt7981|0,1|0,1" # xiaomi ax3000t an8855 variant [with MULTI_LAYOUT]
            ["ruijie_rg-x60"]="mt7986|0,1|0,1" # Ruijie RG-X60 [with MULTI_LAYOUT]
            ["cudy_tr3000-v1"]="mt7981|0|0,1" # Cudy TR3000 v1
            ["netcore_n60"]="mt7986|0|0,1" # Netcore N60
            ["netcore_n60-pro"]="mt7986|0|0,1" # Netcore N60 Pro
            ["ruijie_ew-6000gx-pro"]="mt7986|0,1|0,1" # Ruijie EW-6000GX Pro [with MULTI_LAYOUT]
          )

          # ===== Backup Target Repository =====
          backup_repo() {
            local ORIGINAL_DIR="$PWD"

            echo "Backup path: ${PATH_backup}"
            mkdir -p ${PATH_backup}
            cp -rf ${PATH_target} ${PATH_backup}
            ls -al ${PATH_backup}

            echo "Changing back to the original directory ${ORIGINAL_DIR}"
            cd "${ORIGINAL_DIR}"
          }

          # ===== Define function to compile U-Boot =====
          # ----- complie_device > split_device_params > exec_build_sh -----
          complie_device() {
            local device=$1
            local params=$2
            IFS='|' read -ra PARAMS <<< "$params"
            split_device_params "$device" "${PARAMS[0]}" "${PARAMS[@]:1}"
          }

          split_device_params() {
            local BOARD=$1
            local SOC=$2
            local OTHER_PARAMS=("${@:3}")
            # 从第三个参数开始获取所有参数，存储到 OTHER_PARAMS 数组中
            local MULTI_LAYOUT_VALUES=${OTHER_PARAMS[0]:-"0"}
            local FIXED_MTDPARTS_VALUES=${OTHER_PARAMS[1]:-"0"}
            IFS=',' read -ra MULTI_LAYOUT_ARRAY <<< "${MULTI_LAYOUT_VALUES}"
            IFS=',' read -ra FIXED_MTDPARTS_ARRAY <<< "${FIXED_MTDPARTS_VALUES}"
            
            for MULTI_LAYOUT in "${MULTI_LAYOUT_ARRAY[@]}"; do
              for FIXED_MTDPARTS in "${FIXED_MTDPARTS_ARRAY[@]}"; do
                cd "${PATH_build}"
                rm -rf "${PATH_target}"
                # 恢复备份的 target 目录
                cp -rf "${PATH_backup}/$(basename "${PATH_target}")" "${PATH_build}"
                cd "${PATH_target}"
                exec_build_sh "${SOC}" "${BOARD}" "${MULTI_LAYOUT}" "${FIXED_MTDPARTS}"
              done
            done
          }

          exec_build_sh() {
            local SOC=$1
            local BOARD=$2
            local MULTI_LAYOUT=$3
            local FIXED_MTDPARTS=$4

            echo -e "Current working directory: $(pwd)"
            echo -e "---------- Compile U-Boot of ${BOARD} ----------"
            SOC=${SOC} BOARD=${BOARD} MULTI_LAYOUT=${MULTI_LAYOUT} FIXED_MTDPARTS=${FIXED_MTDPARTS} ./build.sh
            cp -rf ./output/* ${PATH_output}
          }

          # ===== main function =====
          main() {
            mkdir -p ${PATH_output}
            backup_repo

            if [[ -z "${device}" || "${device,,}" == "all" ]]; then
              echo "Compiling for all devices"
              for BOARD in "${!BOARD_PARAMS[@]}"; do
                complie_device "$BOARD" "${BOARD_PARAMS[$BOARD]}"
              done
            else
              if [[ -n "${BOARD_PARAMS[${device}]}" ]]; then
                echo "Compiling for device: ${device}"
                complie_device "$device" "${BOARD_PARAMS[$device]}"
              else
                echo "Invalid device: ${device}"
                exit 1
              fi
            fi
          }
          main "$@"

      - name: (release.md) Generate
        id: release-md
        working-directory: ${{ env.PATH_target }}
        run: |
          echo -e "Current working directory: $(pwd)"
          # printf "Current working directory: %s\n" "$(pwd)"

          release_md_dir=$(dirname ${{ env.release_md }})
          mkdir -p ${release_md_dir}
          : > ${{ env.release_md }}

          record_to_markdown() {
            local title="$1"
            local content="$2"
            local code_block="${3:-}"
            local format="\n### %s\n%s\n"

            if [[ -n "${code_block}" ]]; then
              format="\n### %s\n\n<details>\n<summary>%s</summary>\n\n\`\`\`%s\n%s\n\`\`\`\n\n</details>\n"
              printf "${format}" "${title}" "${title}" "${code_block}" "${content}" | tee -a ${{ env.release_md }}
            else
              printf "${format}" "${title}" "${content}" | tee -a ${{ env.release_md }}
            fi
          }

          record_to_markdown "Timestamp" "- [x] $(date +"%Y-%m-%d %H:%M:%S %z")"
          record_to_markdown "Repository" "- [x] ${repo_target}"
          record_to_markdown "Repository Branch" "- [x] ${repo_target_branch}"

          # sum_json_content=$(jq '.' "${{ env.metadata_sum_path }}")
          # record_to_markdown "sha256sum" "${sum_json_content}" "json"

          cat ${{ env.release_md }}

          echo "timestamp=$(date +"%y%mw%V")" | tee -a ${GITHUB_OUTPUT}

      - name: Upload to Release
        id: release
        uses: ncipollo/release-action@main
        env:
          timestamp: ${{ steps.release-md.outputs.timestamp }}
          target_ext: "tar"
          tag_release: ${{ steps.git-rev.outputs.git_desc }}
        with:
          name: "${{ env.timestamp }}_${{ env.tag_release }}"
          tag: "${{ env.tag_release }}"
          artifacts: "${{ env.PATH_output }}/*"
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: "${{ secrets.GITHUB_TOKEN }}"
